function [fitresult, gof] = createFits(centers, counts)
%CREATEFITS(CENTERS,COUNTS)
%  Create fits.
%
%  Data for 'untitled fit 6' fit:
%      X Input : centers
%      Y Output: counts
%  Data for 'untitled fit 7' fit:
%      X Input : centers
%      Y Output: counts
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Mar-2018 19:37:59

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 6'.
[xData, yData] = prepareCurveData( centers, counts );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [812 -57.88925 2.46904093273725 367.174410017559 -53.54675 3.03597065287368 230.89748694958 -44.86175 3.18687312344885 203.42665386457 -39.74725 3.41073374829635];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 6' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'counts vs. centers', 'untitled fit 6', 'Location', 'NorthEast' );
% Label axes
xlabel centers
ylabel counts
grid on

%% Fit: 'untitled fit 7'.
[xData, yData] = prepareCurveData( centers, counts );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [460 -57.6510951551061 1.55892036158956 264.31349066812 -55.0031044917901 1.86900818955973 169.884255856232 -51.1899979366151 2.27200121112222 131.279244010729 -47.0061726885758 2.62250503006838];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 7' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'counts vs. centers', 'untitled fit 7', 'Location', 'NorthEast' );
% Label axes
xlabel centers
ylabel counts
grid on


